apiVersion: v1 
kind: Service
metadata:
  name: nginx 
spec:
  type: {{  .values.service.type }}
  selector:
    app: nginx 
    tier: frontend
  ports:
  - name: nginx
    protocol: "TCP"
    port: {{ .values.service.port }}
    targetPort: 80