apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    tier: frontend
    app: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: expense
      tier: frontend
      app: frontend
  template:
    metadata:
      labels:
        project: expense
        tier: frontend
        app: frontend
    spec: 
      containers:
      - name: frontend
        image: mlndockerhub/frontend:{{ .Values.deployment.imageVersion }}
