apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: {{ .Values.service.type }}
  selector:
    project: expense
    tier: frontend
    app: frontend
  ports:
  - name: frontend
    protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: 80 