apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    project: expense
    app: backend
    tier: backend
  ports:
  - name: backend
    protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: 8080